### ISSUE TITLE
Is this package still supported

### ISSUE THREAD

**Issue by davestewart** [azazdeaz/spaceman#2]
Hello,

Just wondering if this package is still developed / supported?

**Comment by azazdeaz** [comment]
Hi Dave!

Thanks for asking, but

![ddv](https://user-images.githubusercontent.com/2298371/194808760-b0e8c704-b777-4779-899f-4e28f58e7c82.gif)

**Comment by davestewart** [comment]
Ha! Love the GIF.

Well, my ask was a little loaded if I must be honest 😅

I've just released my own spaceman package to manage [monorepo](https://www.toptal.com/front-end/guide-to-monorepos) workspaces:

[![spaceman](https://raw.githubusercontent.com/davestewart/spaceman/master/res/splash.png)](https://github.com/davestewart/spaceman)

And I see you have the [npm package name](https://www.npmjs.com/package/spaceman), but it looks pretty much inactive. I wondered how you might feel about giving it up / [transferring](https://docs.npmjs.com/transferring-a-package-from-a-user-account-to-another-user-account) it?

I've done this before, and the process can be something along these lines:

- [deprecate](https://docs.npmjs.com/cli/v8/commands/npm-deprecate) the semver range `^0.0.0`
- optionally:
    - add a message pointing to your user namespace `@azazdeaz/spaceman`
    - publish existing code to said namespace
- either try the [commands](https://docs.npmjs.com/transferring-a-package-from-a-user-account-to-another-user-account#transferring-a-package-from-a-user-account-to-another-user-account-on-the-command-line) ourselves, or contact npm support to complete the transfer
- I publish my code, and credit you in the readme

Anyway, I understand if you don't want to do this as it is a cool name, but it would be fantastic if you would consider it.

Thanks for getting back to me!

Dave

**Comment by azazdeaz** [comment]
Oh that's cool! I invited you to this repo and to the npm package so you can do the transfer magic. Let me know if you need anything else for it.  
I agree that this is a cool name and i'm happy that someone makes better use of it! :) Thanks, but no need to credit me for this :D  
Your project looks great, good luck with it! :heart:

**Comment by davestewart** [comment]
Hey András,

Thats awesome, thanks so much!

OK, I'll look into that now and will keep you updated.

🙏 🙏 🙏

**Comment by davestewart** [comment]
OK, it's live!

- https://www.npmjs.com/package/spaceman

Thanks so much András. Looking forward to pushing the next minor release to support PNPM then publicising it a bit more and hopefully getting some interest.

🚀
